// Created by iWeb 2.0.4 local-build-20090212

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,449),url:'Lawn_Care_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'Lawn_Care_files/stroke_17.png'},{rect:new IWRect(2,-2,497,4),url:'Lawn_Care_files/stroke_18.png'},{rect:new IWRect(499,-2,4,4),url:'Lawn_Care_files/stroke_19.png'},{rect:new IWRect(499,2,4,449),url:'Lawn_Care_files/stroke_20.png'},{rect:new IWRect(499,451,4,5),url:'Lawn_Care_files/stroke_21.png'},{rect:new IWRect(2,451,497,5),url:'Lawn_Care_files/stroke_22.png'},{rect:new IWRect(-2,451,4,5),url:'Lawn_Care_files/stroke_23.png'}],new IWSize(501,453)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,90),url:'Lawn_Care_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Lawn_Care_files/stroke_9.png'},{rect:new IWRect(1,-1,686,2),url:'Lawn_Care_files/stroke_10.png'},{rect:new IWRect(687,-1,2,2),url:'Lawn_Care_files/stroke_11.png'},{rect:new IWRect(687,1,2,90),url:'Lawn_Care_files/stroke_12.png'},{rect:new IWRect(687,91,2,2),url:'Lawn_Care_files/stroke_13.png'},{rect:new IWRect(1,91,686,2),url:'Lawn_Care_files/stroke_14.png'},{rect:new IWRect(-1,91,2,2),url:'Lawn_Care_files/stroke_15.png'}],new IWSize(688,92)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,121),url:'Lawn_Care_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Lawn_Care_files/stroke_1.png'},{rect:new IWRect(1,-1,678,2),url:'Lawn_Care_files/stroke_2.png'},{rect:new IWRect(679,-1,2,2),url:'Lawn_Care_files/stroke_3.png'},{rect:new IWRect(679,1,2,121),url:'Lawn_Care_files/stroke_4.png'},{rect:new IWRect(679,122,2,2),url:'Lawn_Care_files/stroke_5.png'},{rect:new IWRect(1,122,678,2),url:'Lawn_Care_files/stroke_6.png'},{rect:new IWRect(-1,122,2,2),url:'Lawn_Care_files/stroke_7.png'}],new IWSize(680,123)),shadow_0:new IWShadow({blurRadius:57,offset:new IWPoint(-0.0000,0.0000),color:'#91ff33',opacity:0.750000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Lawn_Care_files/Lawn_CareMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');Widget.onload();applyEffects()}
function onPageUnload()
{Widget.onunload();}
