<?php

$navMatch = "";
$headCode = "";
$phoneNumber = "(214) 557-6975";

function navMatch($match) {
	global $navMatch;
	return (strtolower($navMatch) == strtolower($match))? ' class="selected"':'';
}

$meta = array(
	"author"=>
		"nickelleon", 
	"language"=>
		"en-us", 
	"distribution"=>
		"global", 
	"robots"=>
		"noindex,nofollow,NOODP", 
	"revisit-after"=>
		"3 Days", 
	"title"=>
		"Timberline Lawn and Landscape [Lawn Care] 214.557.6975 Mowing North Dallas and surrounding areas!", 
	"keywords"=>
		"timberline lawn and landscape, lawn care, landscaping, dallas", 	
	"description"=>
		"Timberline Lawn and Landscape - Mowing North Dallas and surrounding areas!"
	);



?>